### ISSUE TITLE
How to fix the error in "error: encountered an unknown key or option: PackageImports"?

### ISSUE THREAD

**Issue by gitfans5** [diegcif/SumsOfSquares.m2#1]
As I tried to install the package to Macaulay 2, I always got an error message "error: encountered an unknown key or option: PackageImports".

Could anyone help me with exactly how to install the package, or how to fix the error?

Many thanks.

**Comment by diegcif** [comment]
Perhaps your version of Macaulay2 is outdated. Please use the latest version.

**Comment by gitfans5** [comment]
Okay, thanks.
