### ISSUE TITLE
What does "stdio:5:7:(3): error: Vector must consist of monomials" actually mean?

### ISSUE THREAD

**Issue by gitfans5** [diegcif/SumsOfSquares.m2#2]
Could you please let me know what does the error message "stdio:5:7:(3): error: Vector must consist of monomials" actually mean, and how to fix it? Many thanks.

**Comment by diegcif** [comment]
How did you obtain this error?

**Comment by gitfans5** [comment]
I think I may have found the cause. Thanks.
